name: tests

on:
  workflow_dispatch:
  push:
  pull_request:

#env:
#  GOPROXY: "https://proxy.golang.org"
#  GO111MODULE: "on"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [stable]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run unit tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Cache downloaded modules
        uses: actions/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |-
            ${{ runner.os }}-go-
